[package]
name = "ddc-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddc-winapi = "0.2.0"
ddc = "0.2.2"
clap = { version = "3.0.0-rc.8", features = ["derive"] }
